### ISSUE TITLE
Adding poetry to backend 

### ISSUE THREAD

**Issue by lucasbotteri** [BraianMilocco/psychoKiller#11]
I think it's a good idea to consider something more robust to handle dependency management and build stuff. [Poetry](https://python-poetry.org/) would be an excellent choice.

## Why
Poetry would let us have 
* [Deterministic builds](https://python-poetry.org/docs/basic-usage/#installing-without-poetrylock) (This means you can guarantee the dependencies for other developers or prod releases) 
* A better way to package and build
* [Automatically adding installed dependencies to the dependency file](https://python-poetry.org/docs/basic-usage/#specifying-dependencies)
* [Easy way to update dependencies in dependencies file](https://python-poetry.org/docs/basic-usage/#installing-dependencies)
* [Manage dependencies by environment](https://python-poetry.org/docs/pyproject/#dependencies-and-dev-dependencies) (development, production)
*[ It automatically handles virtual enviroments](https://python-poetry.org/docs/basic-usage/#using-your-virtual-environment)
* [A nice CLI  ](https://python-poetry.org/docs/cli/)
* [Custom scripts](https://python-poetry.org/docs/pyproject/#scripts)
* [Some project metadata](https://python-poetry.org/docs/pyproject/#the-pyprojecttoml-file)

## How
_Easy_ just [installing poetry](https://python-poetry.org/docs/#installation), [running this command 
](https://python-poetry.org/docs/cli/#init) to init poetry and run [this command  ](https://github.com/python-poetry/poetry/issues/46#issuecomment-450329494) to add dependencies already installed using requirements.txt

Let me know what you think @BraianMilocco

**Comment by BraianMilocco** [comment]
i like it
